apiVersion: v1
kind: Pod
metadata:
  name: compliant-app
  namespace: baseline-test
spec:
  containers:
  - name: app
    image: nginxinc/nginx-unprivileged:1.21
    ports:
    - containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 101
      capabilities:
        drop:
        - ALL
